Repository Tezzmo/PDS_Project, pull requests merged in 2020-05, with the labels that each got.

#10 Data exploration
  .gitignore
  .idea/.gitignore
  nextbike/io/input.py
  nextbike/io/output.py
  notebooks/00_Example.ipynb
  notebooks/Tobi.ipynb
  notebooks/dataExplorationJonas.ipynb
  setup.py
Labels: description

#11 added first visualization of bikes per station
  .gitignore
  nextbike/__init__.py
  nextbike/io/input.py
  nextbike/visualization/__init__.py
  nextbike/visualization/visualize.py
  notebooks/dataExplorationJonas.ipynb
Labels: enhancement

#12 Visualize bikes per station
  .gitignore
  nextbike/io/input.py
  nextbike/io/output.py
  nextbike/visualization/visualize.py
  notebooks/dataExplorationJonas.ipynb
Labels: Visualization, enhancement

#15 Outlier handling
  nextbike/io/input.py
Labels: enhancement

#20 Postal code
  .gitignore
  .idea/.gitignore
  data/input/postleitzahlen-deutschland.geojson
  ml-models/postalCode/nearestNeighbor_PostalCode.pkl
  nextbike/__init__.py
  nextbike/io/input.py
  nextbike/postalCodes/__init__.py
  nextbike/postalCodes/createPostalCodeGrid.py
  nextbike/postalCodes/createPostalCodeMaps.py
  nextbike/postalCodes/mappingToPostalCodeGrid.py
  nextbike/postalCodes/utils.py
  notebooks/Fabian_Test.py
  notebooks/PostalCodeForCoordinates.csv
Labels: enhancement
